### ISSUE TITLE
Can not run ./run-rasa-core.sh

### ISSUE THREAD

**Issue by cakriwut** [sasastarcevic/rasa-core-and-nlu-docker-compose#2]
Hi,
Thanks for providing example. 
Unfortunately, when I tried to run ./run-rasa-core.sh , it stopped and showing error

```bash
usage: train.py [-h] [-o PATH] (-d DATA | -u URL | --endpoints ENDPOINTS) -c
                CONFIG [-t NUM_THREADS] [--project PROJECT]
                [--fixed_model_name FIXED_MODEL_NAME] [--storage STORAGE]
                [--debug] [-v]
train.py: error: one of the arguments -d/--data -u/--url --endpoints is required
./run-rasa-core.sh: line 2: $'\r': command not found
usage: train.py [-h] {default,compare,interactive} ...
train.py: error: unrecognized arguments: --epochs 300
./run-rasa-core.sh: line 4: $'\r': command not found
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/server.py", line 613, in <module>
    raise RuntimeError("Calling `rasa_core.server` directly is "
RuntimeError: Calling `rasa_core.server` directly is no longer supported. Please use `rasa_core.run --enable_api` instead.

```

Do you have any idea how to fix it?

Best regards,

Riwut

**Comment by sasastarcevic** [comment]
Hi,

You should refactore Docker file for rasa and use older version, because sample is created before some time. 

Or you can take official docker setup for latest version of Rasa stack, but then you will need different structure for training files.

Br,
Sasa
